### ISSUE TITLE
Error loading windtun.dll (the Windows release should contain wintun.dll)

### ISSUE THREAD

**Issue by salehmontazeran** [bepass-org/wireguard-go#123]
**Version number**
1.2.1

**Describe the bug**
when I use `--tun-experimental`, I get this error: 
`Error creating interface: Error loading wintun.dll DLL: Unable to load library: The specified module could not be found.`

**Screenshots**
![Screenshot 2024-05-24 231021](https://github.com/bepass-org/warp-plus/assets/19423357/d49d5d3a-cbea-44c4-87a1-fbb938ebcb9c)

**Desktop:**
 - OS: Win 11

**Comment by AliGh1** [comment]
You should check here https://github.com/bepass-org/warp-plus/issues/66

**Comment by markpash** [comment]
Indeed, in order for tun to work on Windows, the `wintun.dll` driver needs to be placed next to the exe.
In the next version I may include this DLL in the release zip. But the future goal is to embed this into the binary, so no extra DLL files.

**Comment by salehmontazeran** [comment]
> Download [Wintun driver](https://www.wintun.net/) and place it beside the `warp-plus.exe`.

@AliGh1 Dude, I know how to fix it. But the user expects that after unzipping the release archive, they can use the .exe file without any issues.



> In the next version I may include this DLL in the release zip. But the future goal is to embed this into the binary, so no extra DLL files.

@markpash Thank you .

**Comment by markpash** [comment]
The wintun.dll is included in the windows releases (v1.2.2)
